name: Build
on:
  push:
    branches:
      - main
    tags: ["v*"]
    paths:
      - Jellyfin.Plugin.Stash/**
      - .github/**

jobs:
  jellyfin:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build app for release
        run: MSBuild -t:Restore,Build -p:RestorePackagesConfig=true -property:Configuration=Release

      - name: Rename Files
        run: ren Jellyfin.Plugin.Stash/bin/Release/net8.0/Stash.dll Jellyfin.Plugin.Stash.dll && ren Jellyfin.Plugin.Stash/bin/Release/net8.0/Stash.pdb Jellyfin.Plugin.Stash.pdb

      - name: "Flag as nightly in build.yaml"
        uses: fjogeleit/yaml-update-action@v0.10.0
        with:
          valueFile: 'build.yaml'
          propertyPath: 'version'
          value: "0.0.0.9000"
          commitChange: false
          updateFile: true

      - uses: vimtor/action-zip@v1.2
        with:
          files: Jellyfin.Plugin.Stash/bin/Release/net8.0/Jellyfin.Plugin.Stash.pdb Jellyfin.Plugin.Stash/bin/Release/net8.0/Jellyfin.Plugin.Stash.dll
          dest: Jellyfin.Plugin.Stash.zip

      - name: "JPRM: Build"
        id: jrpm
        uses: oddstr13/jellyfin-plugin-repository-manager@b9e92867a6aa279d611a5ea80cf61f6358838c39
        with:
          version: "0.0.0.9000"
          verbosity: debug
          path: .
          dotnet-target: "net6.0"
          output: _dist

      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: Jellyfin
          retention-days: 90
          path: |
            Jellyfin.Plugin.Stash.zip
            build.yaml
  emby:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v2

      - name: Build app for release
        run: MSBuild -t:Restore,Build -p:RestorePackagesConfig=true -property:Configuration=Release.Emby

      - name: Rename Files
        run: ren Jellyfin.Plugin.Stash/bin/Release.Emby/netstandard2.1/Stash.dll ./Emby.Plugins.Stash.dll && ren Jellyfin.Plugin.Stash/bin/Release.Emby/netstandard2.1/Stash.pdb ./Emby.Plugins.Stash.pdb

      - uses: vimtor/action-zip@v1.2
        with:
          files: Jellyfin.Plugin.Stash/bin/Release.Emby/netstandard2.1/Emby.Plugins.Stash.pdb Jellyfin.Plugin.Stash/bin/Release.Emby/netstandard2.1/Emby.Plugins.Stash.dll
          dest: Emby.Plugins.Stash.zip

      - uses: actions/upload-artifact@v4
        with:
          if-no-files-found: error
          name: Emby
          retention-days: 90
          path: Emby.Plugins.Stash.zip
  deploy:
    runs-on: ubuntu-latest
    needs: [jellyfin, emby]
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4

      - uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: |
            **/Jellyfin.Plugin.Stash.zip
            **/Emby.Plugins.Stash.zip
            **/build.yaml
